# Generated by Django 4.0 on 2022-02-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_orderitem_order_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_orders',
            new_name='date_orderred',
        ),
    ]
